### ISSUE TITLE
The buffer disappears while gt-buffer-render-follow-p is non-nil

### ISSUE THREAD

**Issue by seagle0128** [lorniu/go-translate#70] opened 2024-05-16 03:09 UTC
AfterI set `gt-buffer-render-follow-p` to non-nil, the buffer will appear and disappear while translating a new word. No issue if querying the same word again.

**Comment by lorniu** [comment] 2024-05-16 14:02
I can't reproduce the issue you mentioned. Can you describe more details?

**Comment by fredericgiquel** [comment] 2024-05-17 07:50
Same issue for me.

Here is the minimal `init.el` for Emacs 29 to reproduce the problem:
```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(use-package go-translate
  :ensure t
  :custom
  (gt-buffer-render-follow-p t)
  (gt-langs '(en fr))
  (gt-default-translator
   (gt-translator
    :taker (gt-taker :prompt t)
    :engines (gt-google-engine)
    :render (gt-buffer-render))))
```

The steps to reproduce are:
- launch Emacs with the previous `init.el` (directly or with `--init-directory=` option)
- `M-x gt-do-translate`
- enter a word you want to translate

Additionnal info: the problem also occurs when using [`popper`](https://github.com/karthink/popper) to handle `go-translate` buffer.

**Comment by seagle0128** [comment] 2024-05-17 10:10
I make a recording, and hope it's clear.

![gt](https://github.com/lorniu/go-translate/assets/140797/efe763a9-5ba7-48f6-9230-7c06b9183ea2)

**Comment by lorniu** [comment] 2024-05-17 13:24
This issue only happens on Windows. This may be a bug of emacs `url.el`. 

I fixed in the latest commit, may it be ok. Please test.

**Comment by seagle0128** [comment] 2024-05-18 04:28
Thank you! But it seems stopping to release the package to mepla.

**Comment by fredericgiquel** [comment] 2024-05-18 08:42
I tested it. The issue is fixed for me.

Thanks.

**Closed** 2024-05-21 00:43 UTC
