### ISSUE TITLE
Function: go-translate-kill-ring-save doesn't work properly.

### ISSUE THREAD

**Issue by ndistqt** [lorniu/go-translate#5] opened 2020-09-13 11:10 UTC
Invoking the function go-translate-kill-ring-save doesn't save the result in the kill ring.
(Thank you for your great work btw.)

**Comment by lorniu** [comment] 2020-09-13 12:39
I can't reproduce this problem, but the implementation of `go-translate-kill-ring-save` is very simple, just a simple `kill-new` call.

So please execute code like `(kill-new "hello world")` to check whether it is normal. In addition, with `C-h f kill-new` checks whether there is any advice on `kill-new`.

If you still have problems, please provide more descriptions.

**Comment by ndistqt** [comment] 2020-09-13 12:57
Have I misunderstood what should happen after you run the command go-translate-kill-ring-save?
I thought it would contain the result of the translation afterwards?

**Comment by lorniu** [comment] 2020-09-13 13:13
You can have a try in `*scratch*` buffer, select some text, call `go-translate-kill-ring-save`, and then press `C-y`.

Then the current translation result will be inserted at the current position.

That's it.

**Comment by ndistqt** [comment] 2020-09-13 13:24
Maybe there is something wrong with my emacs config, because after doing `go-translate-kill-ring-save` , the kill ring just contains the word that should have been translated.

**Comment by lorniu** [comment] 2020-09-13 13:44
First of all, make sure `go-translate` can do the right thing. 

The `go-translate-kill-ring-save` just redirect the result of `go-translate` to kill-ring.

**Comment by ndistqt** [comment] 2020-09-13 13:51
It seems to have problems now loading it at all. Yesterday it was working. Can I read the error messages somewhere?
<img width="355" alt="emacs@2x" src="https://user-images.githubusercontent.com/17615164/93019684-ddbb4480-f5d8-11ea-9030-c221abcbf9c9.png">

**Comment by lorniu** [comment] 2020-09-13 14:00
Not the issue.

You may use `M-x go-translate-change-local-and-target-language` to see the proper value of  translate direction. I don't think `ger` can be correctly identified by Google.

**Closed** 2020-09-13 17:26 UTC
